### ISSUE TITLE
2Dアクション(Platformer)のおもちの画像

### ISSUE THREAD

**Issue by hamatani63** [Yuumayay/YuumayayGodotBook1#5]
おもちの画像 omochi_dot_anim.png が見当たりません。
※書籍(初版)p.284の図2-48で提示されている画像です

リポジトリ内の素材集＞プラットフォーマーの素材へ追加いただけると嬉しいです。
よろしくお願いします。

**Comment by mofukuma** [comment]
ご連絡ありがとうございます。ここは分冊版のリポジトリなので2Dプラットフォーマーのおもちの画像はありません。
以下の①＋②のリポジトリの素材集データをダウンロードしてください。
https://github.com/Yuumayay/YuruttoGodotBook
